version: '3.8'
services:
  java-maven-app:
      image: gouda99/my-repo:jma-500.0
      ports:
        - 8080:8081
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd

  