version: '3.8'
services:
  java-maven-app:
      image: gouda99/my-repo:Jma-1.1.2-13
      ports:
        - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd

  